[project]
name = "smartfin-tools"
version = "0.1.0"
description = "Smartfin Tools"
authors = [
    {name = "Nathan Hui",email = "nthui@ucsd.edu"}
]
license = {text = "UCSD"}
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "pandas (>=2.2.3,<3.0.0)",
    "numpy (>=2.2.6,<3.0.0)",
    "pyserial (>=3.5,<4.0)",
    "matplotlib (>=3.10.3,<4.0.0)"
]
packages = [
    { include = "smartfin" },
]

[tool.poetry]

[tool.poetry.scripts]
sfDownloader = 'smartfin.sfDownloader:sfDownloader'
sfFlogDownloader = 'smartfin.sfDownloader:flogDownloader'
sfPlotter = 'smartfin.sfPlotter:main'
sfConvert = 'smartfin.sfConvert:main'
sfTempCalibrator = 'smartfin.temp_calibrator:main'

[tool.poetry.group.dev.dependencies]
pytest = "^8.4.0"
autopep8 = "^2.3.2"
pylint = "^3.3.7"

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.semantic_release]
version_variables = ["smartfin/__init__.py:__version__"]
version_toml = [
    "pyproject.toml:tool.poetry.version",
]
assets = []
commit_message = "{version}\n\nAutomatically generated by python-semantic-release"
commit_parser = "angular"
logging_use_named_masks = false
major_on_zero = true
tag_format = "v{version}"

[tool.semantic_release.branches.main]
match = "(main|master)"
prerelease = false
prerelease_token = "rc"

[tool.semantic_release.changelog]
template_dir = "templates"
changelog_file = "CHANGELOG.md"
exclude_commit_patterns = []

[tool.semantic_release.changelog.environment]
block_start_string = "{%"
block_end_string = "%}"
variable_start_string = "{{"
variable_end_string = "}}"
comment_start_string = "{#"
comment_end_string = "#}"
trim_blocks = false
lstrip_blocks = false
newline_sequence = "\n"
keep_trailing_newline = false
extensions = []
autoescape = true

[tool.semantic_release.commit_author]
env = "GIT_COMMIT_AUTHOR"
default = "semantic-release <semantic-release>"

[tool.semantic_release.commit_parser_options]
allowed_tags = ["build", "chore", "ci", "docs", "feat", "fix", "perf", "style", "refactor", "test"]
minor_tags = ["feat"]
patch_tags = ["fix", "perf"]

[tool.semantic_release.remote]
name = "origin"
type = "github"
ignore_token_for_push = false

[tool.semantic_release.remote.token]
env = "GH_TOKEN"

[tool.semantic_release.publish]
dist_glob_patterns = ["dist/*"]
upload_to_vcs_release = true